baseURL = "https://ringomaziwa.github.io/Ringomaziwa-github-io/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "苹果乐园"
theme = "diary"
date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']

[[menu.main]]
url = "/categories"
name = "苹果园"
weight = 1

[[menu.main]]
url = "/tags"
name = "贴标签"
weight = 2

[[menu.main]]
url = "/posts"
name = "摘苹果"
weight = 3

[params]
enableReadingTime=true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    hardWraps = true