baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '苹果乐园'
theme = "diary"

[[menu.main]]
url = "/categories"
name = "目录"
weight = 1

[[menu.main]]
url = "/tags"
name = "标签"
weight = 3

[[menu.main]]
url = "/posts"
name = "文章"
weight = 2

[[menu.main]]
url = "/index.xml"
name = "友谊山丘"
weight = 4